Resources:
  MySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      GenerateSecretString:
        GenerateStringKey: 'password'
        SecretStringTemplate: '{"username": "test-user"}'